title: YE Utku
description: Yusuf Eren Utku's Personal Website
baseurl: 
url: https://yerenutku.github.io

remote_theme: piazzai/hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never

color_hover: green-9

quotes: values
lowercase: keys
  